import dash
from dash import dcc, html
import dash_bootstrap_components as dbc
import os
import csv


dash.register_page(__name__,path='/khoka_glossary')

# Define the navigation bar with the dropdown menu

portada =  dbc.Row(
        [
            html.Img(src="/assets/h_glosa_1.webp",style={"width": "100%",'marginTop':'3%','marginBottom':'3   %'},className="center-image"),
        ]
                )

glosario = dbc.Container(
    dbc.Row([
                dbc.Row(className="espaciado_96_esc espaciado_96_mov"),
                html.Div("GLOSARIO", className="body-title-green"),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 

                html.Div(["Ácido"],className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un ácido es una sustancia que, al disolverse en agua, produce una solución con un pH menor a 7."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Ácido graso poliinsaturado",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Los ácidos grasos poliinsaturados son un tipo de grasa saludable presente en la dieta. Se encuentran tanto en alimentos de origen vegetal como animal, como el salmón, los aceites vegetales, y algunas nueces y semillas. Son beneficiosos para la salud, al igual que los ácidos grasos monoinsaturados. Estas grasas ayudan a reducir el colesterol malo en la sangre y pueden disminuir el riesgo de enfermedades cardíacas."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("ADN",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["El ácido desoxirribonucleico, conocido también por las siglas ADN, es una molécula que contiene las instrucciones genéticas usadas para el desarrollo y funcionamiento de todos los organismos vivos y algunos virus. Es fundamental para la herencia genética."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Agente desecante",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un agente desecante es un material que absorbe agua del ambiente, usado para mantener productos y ambientes secos."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Alcaloide",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Los alcaloides son compuestos naturales que las plantas producen mediante el metabolismo secundario. Estos contienen nitrógeno en su estructura molecular y son conocidos por sus potentes efectos sobre el cuerpo, incluso en dosis pequeñas. Se utilizan en medicina para aliviar el dolor y tratar enfermedades mentales. Ejemplos destacados de alcaloides incluyen la cafeína en el café y la nicotina en el tabaco, ambos estimulantes; la cocaína de la planta de coca, que además es un anestésico local; y la morfina de la amapola, empleada como analgésico."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Aminoácidos",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Los aminoácidos son los bloques constructores de las proteínas en el cuerpo. Cada aminoácido está compuesto por un grupo amino (NH2) y un grupo carboxilo (COOH) en su estructura molecular."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Aminoácidos esenciales",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Los aminoácidos esenciales son los aminoácidos que el cuerpo humano no puede sintetizar y, por lo tanto, deben ser obtenidos a través de la dieta. Existen nueve aminoácidos esenciales: histidina, isoleucina, leucina, lisina, metionina, fenilalanina, treonina, triptófano y valina."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Aminoácidos no esenciales",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Los aminoácidos no esenciales son aquellos que el cuerpo humano puede sintetizar por sí mismo, por lo que no es necesario obtenerlos exclusivamente a través de la dieta. Los aminoácidos no esenciales incluyen: alanina, arginina, asparagina, ácido aspártico, cisteína, ácido glutámico, glutamina, glicina, prolina, serina y tirosina."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Anestésico",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un anestésico es un medicamento utilizado para inducir anestesia, lo cual provoca una pérdida reversible de sensibilidad o conciencia. Los anestésicos se clasifican en dos tipos: los generales, que causan una pérdida reversible de la conciencia, y los locales, que provocan una pérdida reversible de sensibilidad en una región específica del cuerpo sin afectar la conciencia."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Átomo",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["El átomo es la partícula más pequeña de un elemento químico que conserva todas sus propiedades químicas. Consiste en un núcleo con carga positiva, que contiene protones y neutrones, constituyendo aproximadamente el 99.9% de la masa del átomo. Los electrones, que tienen una carga negativa y son mucho más ligeros, orbitan alrededor del núcleo y determinan el tamaño del átomo."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("ATP (Adenosin trifosfato) ",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["El ATP (Adenosín trifosfato) es una molécula esencial para el metabolismo energético de las células. Está compuesto por tres grupos fosfato, una base nitrogenada llamada adenina y un azúcar de tipo pentosa llamado ribosa. El ATP se produce en las mitocondrias de las células animales y en los cloroplastos de las plantas. Esta molécula actúa como una batería de energía para las células, suministrando la energía necesaria para numerosos procesos enzimáticos y reacciones químicas que facilitan la catálisis y otras funciones vitales."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Base nitrogenada ",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Las bases nitrogenadas son compuestos orgánicos con una estructura cíclica que contienen dos o más átomos de nitrógeno. Son componentes esenciales de los nucleósidos, nucleótidos, nucleótidos cíclicos, dinucleótidos y ácidos nucleicos. En el ADN, las bases nitrogenadas se representan con las letras A (adenina), T (timina), G (guanina) y C (citosina). Estas bases se emparejan de manera específica (A con T y G con C) para formar la estructura de doble hélice del ADN, permitiendo el almacenamiento y transmisión de la información genética."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Bencina",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Es una mezcla de hidrocarburos de bajo peso molecular, como el pentano, el hexano y el heptano. Estos componentes tienen puntos de ebullición que varían entre 40 y 60 grados Celsius, lo que permite su uso en diversas aplicaciones industriales y comerciales."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Biosíntesis",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Biosíntesis es el proceso mediante el cual los organismos vivos utilizan enzimas para convertir moléculas simples en otras más complejas a lo largo de múltiples etapas reaccionarias. Este proceso es fundamental para la formación de compuestos bioquímicos esenciales"]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Carbono asimétrico",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un carbono asimétrico es un átomo de carbono que está unido a cuatro átomos o grupos diferentes. Esta estructura única le permite tener actividad óptica, lo que significa que puede desviar la luz polarizada cuando se observa con un polarímetro. Los carbonos asimétricos se encuentran comúnmente en azúcares, aminoácidos y diversos compuestos orgánicos. Esta propiedad es fundamental en la química y la biología, ya que la forma en que estas moléculas interactúan puede depender de su estructura tridimensional específica."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Carboxilo",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["En química orgánica, el carboxilo es un grupo funcional que se compone de un átomo de carbono unido a dos átomos de oxígeno. En este grupo, uno de los oxígenos está unido al carbono mediante un doble enlace, y el otro oxígeno está unido al carbono a través de un enlace simple, y a su vez, este oxígeno está unido a un átomo de hidrógeno u otro elemento, como sodio o litio. Este grupo funcional es característico de los ácidos carboxílicos, que se encuentran en una variedad de compuestos orgánicos esenciales para la vida, como los aminoácidos y los ácidos grasos."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Coenzima",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una coenzima es una pequeña molécula que se une a una enzima y es crucial para su función. Ayuda a transferir grupos químicos, electrones o átomos de hidrógeno durante las reacciones químicas en el cuerpo. Las coenzimas son esenciales para muchas funciones metabólicas y a menudo derivan de vitaminas, como la vitamina B12."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Cofactor",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un cofactor es un compuesto químico no proteico o un ion metálico necesario para que una enzima funcione como catalizador. Los cofactores actúan como moléculas auxiliares, facilitando las transformaciones bioquímicas dentro del organismo. Sin estos cofactores, muchas enzimas no podrían realizar sus funciones correctamente, lo que afectaría numerosos procesos biológicos esenciales. Los cofactores pueden ser iones metálicos, como el magnesio o el zinc, o moléculas orgánicas, conocidas como coenzimas, como las vitaminas."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Colesterol LDL",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["El colesterol LDL, o malo, es una sustancia grasa que puede acumularse en las arterias, aumentando el riesgo de enfermedades del corazón. Se encuentra en la sangre y proviene tanto del hígado como de alimentos como la carne y los productos lácteos. Aunque el cuerpo necesita algo de colesterol para funcionar, niveles altos de LDL pueden ser peligrosos. En contraste, el colesterol HDL, o bueno, ayuda a eliminar el colesterol del cuerpo llevándolo al hígado."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Compuesto",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un compuesto es una sustancia que resulta de la combinación química de dos o más elementos de la tabla periódica. Cada compuesto se representa mediante una fórmula molecular que indica la proporción exacta de los elementos que lo constituyen. Por ejemplo, el agua se representa como H2O, indicando dos átomos de hidrógeno y uno de oxígeno."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Compuesto químico",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un compuesto químico es una sustancia formada por la unión de dos o más elementos diferentes de la tabla periódica. Cada compuesto se caracteriza por una fórmula química específica que indica la composición exacta de sus elementos. Por ejemplo, el agua (H2O) está compuesta por dos átomos de hidrógeno y uno de oxígeno."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Configuración cis-trans",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div([": La configuración cis-trans es un tipo de isomería en moléculas con dobles enlaces de carbono o anillos cíclicos. En la configuración cis, los grupos sustituyentes están en el mismo lado del doble enlace; en la configuración trans, están en lados opuestos. Por ejemplo, el ácido maleico (cis) y el ácido fumárico (trans) tienen la misma fórmula molecular (C4H4O4) pero diferente disposición de sus grupos carboxílicos."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Daño oxidativo",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["El daño oxidativo ocurre cuando hay un desequilibrio entre la producción de especies reactivas de oxígeno (radicales libres) y la capacidad del organismo para contrarrestar estos compuestos y reparar el daño que causan. Este desequilibrio es responsable de muchas enfermedades degenerativas, incluyendo Parkinson, Alzheimer y arteriosclerosis. "]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Disolvente",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["También llamado solvente, un disolvente es una sustancia, generalmente líquida, que puede disolver otras sustancias sin alterarlas químicamente para formar una solución."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Decantación",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["La decantación es un método de separación empleado para dividir componentes de mezclas heterogéneas, especialmente útil para separar líquidos que tienen diferentes densidades. Este proceso permite que el líquido más denso se asiente en el fondo y el menos denso permanezca encima, facilitando su separación."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Elemento",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un elemento es una sustancia química pura constituida exclusivamente por átomos que tienen el mismo número de protones en su núcleo atómico, lo cual define su identidad única en la tabla periódica."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Electrón",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un electrón es una partícula subatómica con carga eléctrica negativa, representada por el símbolo e-. Los electrones carecen de componentes o subestructuras detectables, lo que los clasifica como partículas elementales."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Enantiómero",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Los enantiómeros son compuestos que son imágenes especulares no superponibles entre sí, como las manos. Tienen la misma fórmula molecular pero diferente disposición espacial. Esta isomería se llama isomería óptica y los enantiómeros se clasifican como R (recto) o S (sinister). La isomería óptica se detecta con un polarímetro, que mide cómo una solución desvía la luz polarizada. Esta desviación puede ser hacia la derecha o hacia la izquierda, y se usa para determinar la concentración de compuestos, como el azúcar en bebidas."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Energía",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["La energía es la capacidad para realizar trabajo o inducir cambios físicos, es una propiedad fundamental de la naturaleza que se manifiesta en diferentes formas, como mecánica, térmica, eléctrica, química, nuclear y otras. Esta capacidad puede ser transferida entre sistemas y convertida de una forma a otra, pero no puede ser creada ni destruida (primera ley de la termodinámica)."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Enzima",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una enzima es una proteína que acelera una reacción bioquímica en el metabolismo."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Exfoliante",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un exfoliante es un producto que elimina las células muertas de la piel."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Enantiómero",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Los enantiómeros son compuestos que son imágenes especulares no superponibles entre sí, como las manos. Tienen la misma fórmula molecular pero diferente disposición espacial. Esta isomería se llama isomería óptica y los enantiómeros se clasifican como R (recto) o S (sinister). La isomería óptica se detecta con un polarímetro, que mide cómo una solución desvía la luz polarizada. Esta desviación puede ser hacia la derecha o hacia la izquierda, y se usa para determinar la concentración de compuestos, como el azúcar en bebidas."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Enzima ",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una enzima es una proteína que acelera una reacción bioquímica en el metabolismo."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Fase",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una fase determina un estado físico distinto dentro de un sistema, caracterizado por propiedades físicas y químicas uniformes. Comúnmente, se refiere a las formas distintas en las que la materia se presenta, como sólido, líquido, gas, o plasma. En un sistema heterogéneo, diferentes fases están separadas por fronteras claramente definidas, como se puede observar en una mezcla de agua y aceite."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Fotosíntesis",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["La fotosíntesis es el proceso biológico mediante el cual las plantas, algas y algunas bacterias utilizan la energía de la luz solar para convertirla en energía química almacenada en moléculas de azúcares, principalmente glucosa. Durante la fotosíntesis, estos organismos capturan dióxido de carbono (CO2) del aire y agua (H2O) del suelo, y bajo la influencia de la luz solar, los transforman en glucosa y oxígeno. El oxígeno se libera como un subproducto vital para la respiración de la mayoría de las formas de vida en la Tierra. Este proceso es fundamental no solo para la supervivencia de las plantas y otros organismos fotosintéticos, sino también para mantener y sustentar la vida en el planeta, al producir la mayor parte del oxígeno atmosférico y ser la base de las cadenas alimenticias."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Inmiscible ",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una sustancia inmiscible no se mezcla y queda separada en fases o formando una suspensión. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Gen",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un gen es la unidad funcional y física de la herencia que se transmite de padres a hijos. Los genes son segmentos específicos de ADN ubicados en los cromosomas, y cada uno contiene la información necesaria para producir proteínas específicas, las cuales desempeñan funciones esenciales en el crecimiento, desarrollo y funcionamiento del organismo. Además de la síntesis de proteínas, algunos genes tienen roles reguladores que afectan la expresión de otros genes, influyendo en la actividad y la estructura celular sin codificar proteínas directamente. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Grupo metilo ",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un grupo metilo es una estructura molecular formada por un átomo de carbono unido a tres átomos de hidrógeno, representada como CH3 - .Se encuentra en muchos compuestos orgánicos y se deriva del metano (CH4), que tiene un átomo de carbono y cuatro átomos de hidrógeno."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Ion ",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un ion es una partícula con carga eléctrica, formada por un átomo o una molécula que ha ganado o perdido electrones. Si tiene carga positiva, se llama catión; si tiene carga negativa, se llama anión."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Isomero ",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un isómero es una molécula que tiene la misma fórmula molecular que otra, pero con una disposición diferente de sus átomos. Existen varios tipos de isómeros, incluyendo isómeros de cadena (diferente estructura del esqueleto de carbono), isómeros de posición (diferente ubicación de un grupo funcional), isómeros ópticos (diferente orientación espacial que afecta la actividad óptica), e isómeros configuracionales o cis-trans (diferente disposición alrededor de un doble enlace o anillo)."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Luz",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["La luz es una forma de radiación electromagnética visible para el ojo humano. Se transmite en ondas que, al reflejarse en las superficies, iluminan los objetos y nos permiten ver colores. La longitud de onda de la luz visible, que es solo una pequeña parte del espectro electromagnético, varía desde aproximadamente 400 nanómetros (violeta) hasta cerca de 700 nanómetros (rojo). Más allá de estos límites, están la luz ultravioleta, que tiene longitudes de onda más cortas que el violeta, y la luz infrarroja, que tiene longitudes de onda más largas que el rojo, ambas invisibles al ojo humano. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Luz ultravioleta (UV)",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["La luz ultravioleta (UV) es una forma de radiación electromagnética situada en el espectro entre la luz visible y los rayos X. Se extiende en longitudes de onda desde 100 nanómetros hasta 400 nanómetros y es invisible al ojo humano. La luz UV proviene principalmente del sol, pero también puede ser emitida por fuentes artificiales como lámparas UV y láseres. Aunque tiene aplicaciones útiles en medicina, esterilización y fotografía, la exposición prolongada a la luz ultravioleta puede tener efectos adversos para la salud, como quemaduras solares, daño ocular y aumento del riesgo de cáncer de piel debido a su capacidad para dañar el ADN celular."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Mezcla",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una mezcla es una combinación física de dos o más sustancias en la que cada componente conserva sus propiedades químicas individuales. Las sustancias en una mezcla no se combinan químicamente y, por lo tanto, pueden ser separadas por medios físicos como la filtración, la centrifugación, la decantación, o la destilación."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Mezcla homogénea",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una mezcla homogénea es un tipo de mezcla en la que los componentes están uniformemente distribuidos a lo largo de la mezcla y no se pueden distinguir a simple vista. Las soluciones, como el aire, el vinagre o una solución acuosa de sal, son ejemplos de mezclas homogéneas. A nivel molecular, la mezcla presenta una fase única continua."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Mezcla heterogénea",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una mezcla heterogénea es una mezcla en la que los componentes se pueden identificar visualmente porque no están uniformemente distribuidos. Estas mezclas contienen dos o más fases visibles, cada una de las cuales tiene propiedades químicas distintas. Ejemplos comunes de mezclas heterogéneas incluyen arena mezclada con agua, ensalada de frutas y hormigón. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Miscible ",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Miscible se refiere a la capacidad de dos o más sustancias de mezclarse completamente entre sí para formar una solución homogénea. Esto significa que, al combinarse, se integran de manera uniforme en una sola fase, sin separarse, en ciertos rangos de temperatura, presión y composición. Un ejemplo común es el alcohol y el agua, que al mezclarse forman una solución uniforme."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Molécula",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una molécula es una agrupación definida de dos o más átomos unidos químicamente, que constituye la unidad más pequeña de una sustancia química pura y conserva todas sus propiedades características. Las moléculas pueden variar en tamaño desde simples diatómicas, como el oxígeno molecular (O2), hasta macromoléculas complejas como el ADN y las proteínas, que pueden contener decenas a miles de átomos unidos en estructuras específicas. Los enlaces que mantienen unidos los átomos en una molécula pueden ser covalentes, donde los átomos comparten electrones, o iónicos, donde los átomos se atraen debido a cargas opuestas. Esta estructura y composición definen las propiedades físicas y químicas de la sustancia."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Mol",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["El mol es la unidad del Sistema Internacional de Unidades utilizada para medir la cantidad de sustancia. Un mol equivale exactamente al número de Avogadro, es decir, 6.02214076x10^23 entidades elementales, que pueden ser átomos, moléculas, iones, o cualquier otra unidad básica que compone una sustancia. Esta definición permite a los científicos cuantificar y comparar cantidades de sustancias a nivel atómico y molecular de manera precisa.  "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Narcótico",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["El término narcótico se utiliza generalmente para describir sustancias que inducen sueño, relajación muscular, y una pérdida de la sensibilidad y la conciencia. En el contexto médico, los narcóticos son una clase de medicamentos que en su mayoría son analgésicos opioides, que se utilizan principalmente para el manejo del dolor severo. Estos compuestos actúan en el sistema nervioso central para aliviar el dolor, pero también pueden suprimir la respiración, causar somnolencia y, a menudo, dependencia física y psicológica si se usan inadecuadamente o durante períodos prolongados. Ejemplos comunes incluyen morfina, fentanilo y codeína. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Neutrón",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["El neutrón es una partícula subatómica sin carga eléctrica, ubicada en el núcleo de casi todos los átomos, junto con los protones. Los neutrones tienen una masa ligeramente mayor que la de los protones y no poseen carga eléctrica neta. Su presencia en el núcleo contribuye a la estabilidad del mismo, ya que los neutrones pueden reducir las fuerzas de repulsión electrostática entre los protones cargados positivamente. Los neutrones juegan un papel crucial en muchos procesos nucleares, incluyendo las reacciones de fisión y fusión nuclear. Además, son esenciales en la física de partículas y tecnología nuclear, como la generación de energía y la medicina nuclear. Un ejemplo notable es el deuterio, un isótopo común del hidrógeno, que consta de un solo protón y  de un neutrón."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Neurotransmisor",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un neurotransmisor es una biomolécula que transmite información entre las células del sistema nervioso. Funciona como un mensajero químico, enviando señales desde una neurona a otra, o hacia una célula muscular o una glándula, a través de un proceso llamado sinapsis. Los neurotransmisores son esenciales para la comunicación en el cerebro y el cuerpo, y juegan un papel crucial en funciones como el movimiento, las emociones y el pensamiento."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Núcleo atómico",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["El núcleo atómico es la parte central del átomo, donde se concentra aproximadamente el 99.9% de su masa total y que posee una carga positiva. El núcleo está compuesto principalmente por dos tipos de partículas subatómicas: protones, que tienen carga positiva, y neutrones, que no tienen carga. Estas partículas están ligadas entre sí por una fuerza extremadamente poderosa conocida como la fuerza nuclear fuerte, la cual es esencial para la estabilidad del núcleo. La cantidad de protones en el núcleo determina la identidad del elemento químico (por ejemplo, el hidrógeno tiene un protón, el helio tiene dos, el carbono tiene seis y el uranio tiene 92). Los átomos del mismo elemento que difieren en el número de neutrones se conocen como isótopos. Estos isótopos pueden exhibir propiedades físicas y químicas diferentes, incluyendo la estabilidad y la radioactividad. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Nucleótido",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Los nucleótidos son las unidades básicas estructurales y funcionales que constituyen los ácidos nucleicos, como el ADN y el ARN. Cada nucleótido está compuesto por tres componentes: una base nitrogenada, que puede ser adenina (A), timina (T), citosina (C) o guanina (G) en el ADN (uracilo (U) reemplaza a la timina en el ARN), un azúcar de cinco carbonos, que es la ribosa en el ARN y desoxirribosa en el ADN, y un grupo fosfato. Estos elementos están conectados en secuencias específicas para formar largas cadenas de ADN y ARN que almacenan y transmiten información genética esencial para el desarrollo, funcionamiento y reproducción de los organismos vivos. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Oxidación",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["La oxidación es el proceso químico mediante el cual un átomo, ión o molécula pierde electrones durante una reacción química. Tradicionalmente, este término se asociaba con las reacciones donde el oxígeno se combinaba con otras sustancias, incrementando así el contenido de oxígeno del compuesto. Sin embargo, en un sentido más amplio, la oxidación no necesariamente involucra oxígeno. Se define modernamente en química como la pérdida de electrones, lo cual puede afectar las propiedades químicas de la sustancia involucrada y a menudo ocurre simultáneamente con la reducción, donde otra sustancia gana los electrones perdidos en el proceso de oxidación. Este conjunto de procesos complementarios se conoce como reacción redox (reducción-oxidación)."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Partícula subatómica",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una partícula subatómica es una partícula más pequeña que un átomo, la cual puede ser elemental o compuesta. Las partículas elementales, como los electrones, son componentes básicos de la materia que no están formados por partículas más pequeñas y poseen características físicas fundamentales. Por otro lado, las partículas compuestas, como los protones y los neutrones, están formadas por la unión de partículas aún más pequeñas llamadas quarks, unidas por la fuerza nuclear fuerte. Estas partículas subatómicas juegan roles cruciales en la estructura y el comportamiento de los átomos y, por ende, en todas las propiedades químicas y físicas de la materia. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Patógeno",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un patógeno es un agente infeccioso capaz de causar enfermedad en su huésped. Los patógenos pueden ser de diversas naturalezas biológicas e incluyen virus, bacterias, hongos y parásitos. Cada tipo de patógeno tiene métodos únicos de invasión y replicación dentro del huésped. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Peso molecular",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["El peso molecular, más precisamente conocido como masa molar, es una propiedad física que describe la masa de un mol de moléculas de una sustancia. Se mide en gramos por mol (g/mol). Esta medida indica cuánto pesa un mol de cualquier sustancia química, basado en la suma de las masas de los átomos que componen una molécula de esa sustancia según la tabla periódica." ]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Protón",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["El protón es una partícula subatómica ubicada en el núcleo de un átomo, que posee una carga positiva elemental. La carga de un protón es igual en magnitud pero opuesta en signo a la de un electrón, que tiene carga negativa. Con una masa aproximadamente 1836 veces mayor que la de un electrón, los protones contribuyen significativamente a la masa total del átomo. La cantidad de protones en el núcleo atómico determina el número atómico de un elemento y, por ende, su identidad química. Junto con los neutrones, los protones en el núcleo están ligados por la fuerza nuclear fuerte, que es responsable de mantener la estabilidad del núcleo a pesar de la repulsión electrostática entre los protones cargados positivamente."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Proteínas",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Las proteínas son macromoléculas complejas y esenciales que desempeñan una variedad de funciones críticas dentro de los organismos vivos. Están formadas por cadenas lineales de aminoácidos, cuya secuencia está determinada por los nucleótidos en los genes correspondientes del ADN. Estas secuencias de aminoácidos se pliegan en estructuras tridimensionales específicas que determinan la función de la proteína. Las proteínas son indispensables para prácticamente todos los procesos biológicos, incluyendo la catalización de reacciones metabólicas (enzimas), la regulación de la expresión génica, la transmisión de señales entre y dentro de las células, el soporte estructural en células, tejidos, y el transporte de moléculas a través de membranas celulares. Además, las proteínas juegan un papel crucial en el sistema inmunitario y en el movimiento muscular. Debido a su diversidad funcional y su rol en la base de muchas patologías, son objeto central de numerosas investigaciones en biomedicina y biotecnología."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Radiación",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["La radiación es la emisión y propagación de energía en forma de ondas electromagnéticas o partículas subatómicas que viajan a través del espacio o algún medio. Esta energía puede manifestarse de diversas formas, como la luz visible, las ondas de radio, los rayos ultravioleta, los rayos X, o los rayos gamma en el caso de la radiación electromagnética, o como partículas como los alfa, beta y neutrones en la radiación de partículas. La radiación puede ser natural, como la luz solar que alcanza la Tierra, el calor emitido por el cuerpo humano, o la radiación de elementos radiactivos presentes naturalmente en el medio ambiente. También puede ser artificial, generada por dispositivos humanos como máquinas de rayos X, reactores nucleares o emisores de radiofrecuencia. La radiación tiene numerosas aplicaciones en medicina, industria, investigación y tecnología; sin embargo, la exposición excesiva a ciertos tipos de radiación de alta energía puede ser perjudicial para los seres vivos, causando daños desde quemaduras solares hasta mutaciones genéticas y cáncer."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Reducción",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Reducción es un proceso electroquímico donde un átomo, ion o molécula gana electrones, resultando en la disminución de su estado de oxidación. Este proceso es fundamental en las reacciones redox (reducción-oxidación), donde la reducción se produce simultáneamente con la oxidación, que es la pérdida de electrones por parte de otra especie. Las reacciones de reducción son esenciales en numerosos procesos químicos y biológicos, incluyendo la fotosíntesis, la respiración celular y la generación de energía en baterías. En un sentido más amplio, la reducción también puede referirse a la disminución de la cantidad de oxígeno o el aumento de hidrógeno en una molécula durante una reacción química."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Radical libre",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un radical libre es una especie química altamente reactiva que posee un electrón desapareado en su última capa electrónica, lo que le confiere una gran tendencia a participar en reacciones químicas para alcanzar estabilidad. Los radicales libres se forman generalmente como intermediarios en reacciones químicas a través de la ruptura homolítica de enlaces químicos, donde cada átomo vinculado conserva uno de los electrones del enlace original. Aunque tienen una vida media muy corta, estos radicales pueden iniciar cadenas de reacciones que resultan en cambios significativos en las estructuras moleculares. En biología, los radicales libres son conocidos por su papel en el estrés oxidativo, donde el daño acumulativo a células y tejidos puede contribuir al envejecimiento y a diversas enfermedades, incluyendo cáncer y enfermedades cardiovasculares. Además, los radicales libres tienen aplicaciones industriales en la polimerización, la fabricación de plásticos, y el tratamiento de aguas residuales, entre otros."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Sedante",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un sedante es una sustancia o combinación de sustancias que ejercen un efecto relajante sobre el sistema nervioso central. Los sedantes son comúnmente utilizados para tratar trastornos como la ansiedad y el insomnio, ayudando a reducir la tensión, la agitación y facilitando el sueño. Estos fármacos pueden variar en potencia, desde ligeros sedantes que ayudan a relajar al paciente, hasta hipnóticos más potentes que inducen el sueño."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Síntesis (química)",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["La síntesis química es el proceso por el cual se crean compuestos químicos complejos a partir de reactivos más simples mediante reacciones químicas controladas. Este proceso es fundamental en la química para la fabricación de numerosos productos, desde medicamentos hasta materiales avanzados. La síntesis química implica la formación de enlaces químicos y se lleva a cabo siguiendo métodos y técnicas específicos que permiten obtener el producto deseado con alta pureza y rendimiento. Es utilizada tanto en investigación como en la industria para desarrollar nuevas sustancias y mejorar las propiedades de las ya existentes."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Sustancia (química)",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una Sustancia química es una forma de materia que tiene composición química constante y propiedades características definidas. Las sustancias químicas pueden ser elementos puros, como el oxígeno o el oro, donde todos los átomos son idénticos, o compuestos, que consisten en dos o más elementos químicos unidos en proporciones fijas. Estos compuestos pueden ser orgánicos, que generalmente contienen carbono y otros elementos como hidrógeno, oxígeno, y nitrógeno, y son la base de la química de la vida."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Solubilidad",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Solubilidad es la capacidad de una sustancia, conocida como soluto, para disolverse en otra sustancia llamada disolvente, formando una solución homogénea. La solubilidad de un soluto en un disolvente específico depende de factores como la temperatura, el pH y la presión ambiental. Esta propiedad es fundamental para numerosos procesos en química, biología, farmacología y la vida cotidiana."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Soluto",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Soluto es la sustancia que se disuelve en otra sustancia, conocida como disolvente, para formar una solución. El soluto es generalmente la sustancia en menor cantidad en una mezcla, aunque esto puede variar dependiendo de la solución. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Solución",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Una solución es una mezcla homogénea compuesta por un disolvente y uno o más solutos. En una solución, el soluto se disuelve completamente en el disolvente, resultando en una composición uniforme a nivel molecular."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Tabla periódica",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["La tabla periódica es una representación gráfica de la ley periódica, que establece que las propiedades de los elementos químicos varían de manera periódica en función de sus números atómicos. La tabla está organizada en filas denominadas períodos y columnas llamadas grupos. Los elementos en un mismo grupo comparten comportamientos químicos similares debido a su configuración electrónica. La tabla se divide en cuatro bloques principales, cada uno correspondiente a la configuración electrónica del último electrón añadido: s, p, d y f. Esta organización ayuda a prever relaciones entre las propiedades de los elementos y a entender la estructura de los compuestos que forman. Además, facilita el estudio de las tendencias químicas y físicas de los elementos a lo largo y ancho de la tabla. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Tóxico",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Tóxico se refiere a cualquier sustancia que, al ser ingerida, inhalada, o absorbida por la piel, puede causar daño grave al organismo o incluso la muerte. "]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Xenobiótico ",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Un xenobiótico es una sustancia química que se encuentra en un organismo pero no es producida por él."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),



                
            ],
            className="container-text"
        ))

# Definir los tooltips
tooltips = []


# Define the layout
layout =    [ dbc.Col(
                portada,
                xs={"size": 12, "order": 2},  # Change order to 2 on extra small devices
                sm={"size": 12, "order": 2},  # Change order to 2 on small devices
                md={"size": 12, "order": 3},
                lg={"size": 12, "order": 3},
                xl={"size": 12, "order": 3},
                style={'paddingRight':'0rem','paddingLeft':'0rem'}
                
            ),
            dbc.Col(
                glosario,
                xs={"size": 12, "order": 4},  # Change order to 2 on extra small devices
                sm={"size": 12, "order": 4},  # Change order to 2 on small devices
                md={"size": 12, "order": 4},
                lg={"size": 12, "order": 4},
                xl={"size": 12, "order": 4},
                style={'paddingRight':'0rem','paddingLeft':'0rem'}
            ),
            *tooltips
        ]


